name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy Cloud Function (Gen2)
      run: |
        gcloud functions deploy cisa-threat-intel \
          --gen2 \
          --runtime python311 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point app \
          --region ${{ secrets.GCP_REGION }} \
          --project ${{ secrets.GCP_PROJECT }}
