name: Deploy to Google Cloud Functions (Gen2)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Setup gcloud
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: "beta"

      # Deploy Cloud Function Gen2
      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy cisa-threat-intel \
            --gen2 \
            --runtime python311 \
            --region us-central1 \
            --source . \
            --entry-point app \
            --trigger-http \
            --allow-unauthenticated
